// Downloads the app's typefaces from Fontshare and bundles them locally, so
// the built app never reaches the network for a font.
//
// Cabinet Grotesk carries display type; Switzer carries UI text. Both are free
// for commercial use under the Fontshare licence. Run: npm run fonts

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, '..', 'src', 'fonts')

const REQUEST = [
  'f[]=switzer@400,500,600,700',
  'f[]=cabinet-grotesk@700,800',
  'display=swap',
].join('&')

const slug = (family, weight) =>
  `${family.toLowerCase().replace(/[^a-z]+/g, '-')}-${weight}.woff2`

const css = await (
  await fetch(`https://api.fontshare.com/v2/css?${encodeURI(REQUEST)}`, {
    headers: { 'user-agent': 'Mozilla/5.0' },
  })
).text()

// Pull one (family, weight, woff2 url) triple out of each @font-face block.
const faces = []
for (const block of css.split('@font-face').slice(1)) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1]
  const url = block.match(/url\('([^']+\.woff2)'\)/)?.[1]
  if (family && weight && url) {
    faces.push({ family, weight, url: url.startsWith('//') ? `https:${url}` : url })
  }
}
if (!faces.length) throw new Error('Fontshare returned no @font-face blocks')

await fs.mkdir(OUT, { recursive: true })
const rules = []
for (const face of faces) {
  const name = slug(face.family, face.weight)
  const bytes = Buffer.from(await (await fetch(face.url)).arrayBuffer())
  await fs.writeFile(path.join(OUT, name), bytes)
  rules.push(
    `@font-face {\n` +
      `  font-family: '${face.family}';\n` +
      `  src: url('./fonts/${name}') format('woff2');\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-style: normal;\n` +
      `  font-display: block;\n` +
      `}`,
  )
  console.log(`  ${name}  ${(bytes.length / 1024).toFixed(0)}kB`)
}

await fs.writeFile(
  path.join(HERE, '..', 'src', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Cabinet Grotesk and Switzer, bundled so the app works offline. */\n\n` +
    rules.join('\n\n') +
    '\n',
)
console.log(`\nwrote src/fonts.css with ${faces.length} faces`)
