// Downloads the app's typeface and bundles it locally, so the built app never
// reaches the network for a font.
//
// Only one face is bundled. The UI face is Helvetica Neue, which ships with
// macOS — a deliberate choice for this design rather than a fallback, since
// the direction is Vignelli-era Milanese and Helvetica is the face of it.
//
// Courier Prime is the typewriter: ports on the detail screen, paths, branch
// names, uptime, log output and code all set in it. Run: npm run fonts

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, '..', 'src', 'fonts')

// Google serves woff2 only to a user-agent it believes can read it.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

const css = await (
  await fetch('https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&display=block', {
    headers: { 'user-agent': UA },
  })
).text()

const faces = []
for (const block of css.split('@font-face').slice(1)) {
  // Latin only — the other unicode-range blocks are dead weight here.
  if (!/U\+0000-00FF/.test(block)) continue
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1]
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  if (weight && url) faces.push({ weight, url })
}
if (!faces.length) throw new Error('Google Fonts returned no latin @font-face blocks')

await fs.rm(OUT, { recursive: true, force: true })
await fs.mkdir(OUT, { recursive: true })

const rules = []
for (const face of faces) {
  const name = `courier-prime-${face.weight}.woff2`
  const bytes = Buffer.from(await (await fetch(face.url)).arrayBuffer())
  await fs.writeFile(path.join(OUT, name), bytes)
  rules.push(
    `@font-face {\n` +
      `  font-family: 'Courier Prime';\n` +
      `  src: url('./fonts/${name}') format('woff2');\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-style: normal;\n` +
      `  font-display: block;\n` +
      `}`,
  )
  console.log(`  ${name}  ${(bytes.length / 1024).toFixed(1)}kB`)
}

await fs.writeFile(
  path.join(HERE, '..', 'src', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Courier Prime, bundled so the app works offline. The UI face is\n` +
    `   Helvetica Neue, which ships with macOS and needs no bundling. */\n\n` +
    rules.join('\n\n') +
    '\n',
)
console.log(`\nwrote src/fonts.css with ${faces.length} faces`)
